#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

#include "font.h"


// Simple 4x4 bitmap font renderer.

/*

* each nibble is a line from top to bottom
* each character has a width and height of 1 unit
* a chararacter's x and y are in the center
* kerning is built into the font
* each character has 2 triangles per lit pixel
* each character has 6 vertices per lit pixel
* each vertex has 2 floats (x, y)
* each lit pixel occupies 12 floats (48 bytes)

0xeae0
------

000.
0.0.
000.
....

(-0.5,0.5)   (0.0,0.5)   (0.5,0.5)
     +-----+-----+-----+-----+
     |     |     |     |     |
     | 15  | 14  | 13  | 12  |
     +-----+-----+-----+-----+ (0.5,0.25)
     |     |     |     |     |
     | 11  | 10  |  9  |  8  |
     +-----+-----+-----+-----+ (0.5,0.0)
     |     |     |     |     |
     |  7  |  6  |  5  |  4  |
     +-----+-----+-----+-----+ (0.5,-0.25)
     |     |     |     |     |
     |  3  |  2  |  1  |  0  |
     +-----+-----+-----+-----+
(-0.5,-0.5)  (0.0,-0.5)  (0.5,-0.5)

Each quad is comprised of 2 CCW triangles:

  1     0
  +-----+ 3
  |t1 / |
  |  /  |
  | / t2|
2 +-----+
  4     5

*/

// https://simplifier.neocities.org/4x4.html
static const unsigned short font[] = {
    0xeae0,  // 0
    0x4430,  // 1
    0x2ce0,  // 2
    0xe6e0,  // 3
    0xae20,  // 4
    0xec20,  // 5
    0x8ae0,  // 6
    0xe220,  // 7
    0xeee0,  // 8
    0xea20,  // 9
};

/*

*/

enum {
    QUADS_PER_GLYPH = 16,

    TRIANGLES_PER_QUAD = 2,
    VERTICES_PER_TRIANGLE = 3,
    FLOATS_PER_VERTEX = 2,

    VERTICES_PER_QUAD = TRIANGLES_PER_QUAD * VERTICES_PER_TRIANGLE,
    FLOATS_PER_QUAD = TRIANGLES_PER_QUAD * VERTICES_PER_TRIANGLE * FLOATS_PER_VERTEX,
};

// Generated by:
// python3 scripts/font.py
static const float quads[QUADS_PER_GLYPH][FLOATS_PER_QUAD] = {
    //       top right       top left        bottom left     top right       bottom left     bottom right
    //       x       y       x       y       x       y       x       y       x       y       x       y
    [0]  = {  0.50f, -0.25f,  0.25f, -0.25f,  0.25f, -0.50f,  0.50f, -0.25f,  0.25f, -0.50f,  0.50f, -0.50f },
    [1]  = {  0.25f, -0.25f,  0.00f, -0.25f,  0.00f, -0.50f,  0.25f, -0.25f,  0.00f, -0.50f,  0.25f, -0.50f },
    [2]  = {  0.00f, -0.25f, -0.25f, -0.25f, -0.25f, -0.50f,  0.00f, -0.25f, -0.25f, -0.50f,  0.00f, -0.50f },
    [3]  = { -0.25f, -0.25f, -0.50f, -0.25f, -0.50f, -0.50f, -0.25f, -0.25f, -0.50f, -0.50f, -0.25f, -0.50f },
    [4]  = {  0.50f,  0.00f,  0.25f,  0.00f,  0.25f, -0.25f,  0.50f,  0.00f,  0.25f, -0.25f,  0.50f, -0.25f },
    [5]  = {  0.25f,  0.00f,  0.00f,  0.00f,  0.00f, -0.25f,  0.25f,  0.00f,  0.00f, -0.25f,  0.25f, -0.25f },
    [6]  = {  0.00f,  0.00f, -0.25f,  0.00f, -0.25f, -0.25f,  0.00f,  0.00f, -0.25f, -0.25f,  0.00f, -0.25f },
    [7]  = { -0.25f,  0.00f, -0.50f,  0.00f, -0.50f, -0.25f, -0.25f,  0.00f, -0.50f, -0.25f, -0.25f, -0.25f },
    [8]  = {  0.50f,  0.25f,  0.25f,  0.25f,  0.25f,  0.00f,  0.50f,  0.25f,  0.25f,  0.00f,  0.50f,  0.00f },
    [9]  = {  0.25f,  0.25f,  0.00f,  0.25f,  0.00f,  0.00f,  0.25f,  0.25f,  0.00f,  0.00f,  0.25f,  0.00f },
    [10] = {  0.00f,  0.25f, -0.25f,  0.25f, -0.25f,  0.00f,  0.00f,  0.25f, -0.25f,  0.00f,  0.00f,  0.00f },
    [11] = { -0.25f,  0.25f, -0.50f,  0.25f, -0.50f,  0.00f, -0.25f,  0.25f, -0.50f,  0.00f, -0.25f,  0.00f },
    [12] = {  0.50f,  0.50f,  0.25f,  0.50f,  0.25f,  0.25f,  0.50f,  0.50f,  0.25f,  0.25f,  0.50f,  0.25f },
    [13] = {  0.25f,  0.50f,  0.00f,  0.50f,  0.00f,  0.25f,  0.25f,  0.50f,  0.00f,  0.25f,  0.25f,  0.25f },
    [14] = {  0.00f,  0.50f, -0.25f,  0.50f, -0.25f,  0.25f,  0.00f,  0.50f, -0.25f,  0.25f,  0.00f,  0.25f },
    [15] = { -0.25f,  0.50f, -0.50f,  0.50f, -0.50f,  0.25f, -0.25f,  0.50f, -0.50f,  0.25f, -0.25f,  0.25f },
};

long
font_size(const char* str)
{
    assert(str != NULL);
    long size = 0;

    char c;
    while ((c = *str++) != '\0') {
        c = c - '0';
        assert(c >= 0 && c <= 9);

        unsigned short glyph = font[(unsigned char)c];
        for (long i = 0; i < 4*4; i++) {
            char quad = (glyph >> i) & 1;
            if (quad) {
                size += FLOATS_PER_QUAD * sizeof(float);
            }
        }
    }

    return size;
}

long
font_vertices(const char* str)
{
    assert(str != NULL);
    long vertices = 0;

    char c;
    while ((c = *str++) != '\0') {
        c = c - '0';
        assert(c >= 0 && c <= 9);

        unsigned short glyph = font[(unsigned char)c];
        for (long i = 0; i < 4*4; i++) {
            char quad = (glyph >> i) & 1;
            if (!quad) continue;

            vertices += VERTICES_PER_QUAD;
        }
    }

    return vertices;
}

void
font_print(const char* str, float* buffer, long size)
{
    assert(str != NULL);
    assert(buffer != NULL);
    assert(size >= font_size(str));

    long x = 0;
    long y = 0;

    char c;
    while ((c = *str++) != '\0') {
        c = c - '0';
        assert(c >= 0 && c <= 9);

        unsigned short glyph = font[(unsigned char)c];
        for (long i = 0; i < 4*4; i++) {
            char quad = (glyph >> i) & 1;
            if (!quad) continue;

            for (long v = 0; v < VERTICES_PER_QUAD; v++) {
                *buffer++ = quads[i][v*2 + 0] + x;
                *buffer++ = quads[i][v*2 + 1] + y;
            }
        }

        x += 1;
    }
}
